channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda
  - pyg
  - networkx=3.1
  - numpy
  - scipy
  - wand
  - matplotlib
  - seaborn
  - pandas
  - jupyterlab 
  - wandb
  - netrd
